---
title: 'Homework #3'
author: "Keene Morrow"
date: "5/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)

data <- read_csv("esm204_hw3_data.csv")
```

ESM 204: Incidence of Gas Tax

This homework asks you to examine the distributional effects of a gas tax. The overall questions are: (1) What will be the distributional effects of the tax? (2) How much revenue will be generated for infrastructure repairs? (3) By how much will environmental damage be reduced and who will benefit? (4) What is the role of electric vehicle technology?

You can use the following stylized facts:

- Consumers can be separated into two income groups: “High” and “Low”. The data set provides price (in $) and quantity (in gallons) estimates of demand per day for the two groups. Run regressions to estimate the demand curves for “High” and “Low” income consumers.
- Initially, there is no gas tax.
- The current gas price (without any taxes) is $3.00/gal.
- The marginal cost of producing a gallon of gasoline is linear and has price-intercept of 0. For the purposes of this exercise, you can assume that the country in question is self-contained in supply and demand (you don’t need to worry about global markets).
- Consuming each gallon of gasoline creates an environmental and health externality in the country of approximately \$1.50. In addition, it imposes an externality (from climate change) of about \$0.50 on the rest of the world.


Your assignment is to walk through the following analyses and then draft a memo to the Council of Economic Advisors advising them on the answers to the four questions posed at the top of this page. You should include a technical appendix with responses to the questions below:



1. What is the aggregate daily demand curve for gasoline? What is the supply curve for gasoline? What is the “benefit” to consumers under the status quo? What is the “benefit” to producers under the status quo? What is the environmental cost under the status quo (locally and in the rest of the world)?



2. How is the current consumer benefit divided between “High” and “Low” income consumers?



3. A gas tax of $1.00/gal. is proposed. What would be the effects of this tax on:

a. The amount of gasoline produced and consumed.


b. The price of gasoline.


c. Welfare of “High” income consumers.


d. Welfare of “Low” income consumers.


e. Welfare of gas producers.


f. Local environmental damage.


g. Rest of world environmental damage.


h. Total revenue generated by the tax.


4. Now, assume that all revenue from a tax will be redistributed to the two groups in proportion to their pre-tax consumption of gas. For example, if 80% of the gas was consumed by High income consumers, then they get 80% of the tax revenue. Also assume that “Low” income consumers bear all local environmental costs. For a range of gas taxes (ranging from \$0 - \$5.00/gal), calculate the effects of the tax on:

a. Overall welfare of “High” income consumers


b. Overall welfare of “Low” income consumers


c. Gas producers



5. A new electric car technology is invented and it lowers the demand curves of all income groups by half (vertically). Under these new demand curves, what are the effects on:

a. Gas consumption by “High” income consumers


b. Gas consumption by “Low” income consumers


c. Gas price


d. Local environmental damage from gasoline


e. Rest of world environmental damage from gasoline


6. Compare two situations: (1) Gas tax of $T/gal. but no electric car technology and (2) No gas tax but with electric car technology. What value of T (i.e. what gas tax) makes the local environmental quality equal between these two situations?

